### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/activation/DataSource when starting application

### ISSUE THREAD

**Issue by pkiraly** [DESIR-CodeSprint/trackB#1]
When the application starts it throws and exception

```
java.lang.NoClassDefFoundError: javax/activation/DataSource when starting application
```

**Comment by dominnovak** [comment]
Hello, I would like to resolve this issue. Can you assign me on this?

**Comment by yoannspace** [comment]
Wasn't it already fixed in https://github.com/DARIAH-ERIC/DESIR-CodeSprint-TrackB-BibliographicMetadata/commit/63921a224f5580a66b7fb8935cbe371c960c500f?
@pkiraly @ChristophHubeL3S @dominnovak

**Comment by pkiraly** [comment]
Yes, it was fixed. I close this issue.
